In [2]:
import particle as par
import molecule as mol
import numpy as np

In [2]:
m = mol.molecule(np.asarray([0.2,0.2]),np.asarray([0.8,0.8]),1,2,1,0.5)

In [3]:
p = par.Particle(np.asarray([1,2]),3)

In [4]:
print(p.m)

3


In [5]:
print(p.pos)

[1 2]


In [6]:
print(m.get_displ())

[0.6 0.6]


In [7]:
print(m.get_force())

[-0.6000000000000001, -0.6000000000000001]


In [8]:
print(p.vel)

[0. 0.]


In [9]:
p.m = 4

In [10]:
print(p.m)

4


In [11]:
print(m.get_displ())

[0.6 0.6]


In [12]:
print(m.p2.pos)

[0.8 0.8]


In [13]:
print(m.p2.pos-m.p1.pos)

[0.6 0.6]


In [14]:
m.get_displ()

array([0.6, 0.6])

In [15]:
print(m.get_force())

[-0.6000000000000001, -0.6000000000000001]


In [16]:
arr = [3,4]
unit = []
mag = np.linalg.norm(arr)
for i,e in enumerate(arr):
    unit.append(arr[i]/mag)

In [17]:
print(unit)

[0.6, 0.8]


In [18]:
m.displ

array([0.6, 0.6])

In [19]:
m.get_force()

[-0.6000000000000001, -0.6000000000000001]

In [20]:
m = mol.molecule(np.asarray([1,1]),np.asarray([2,2]),1,2,3,0.5)

In [26]:
m.get

[]

In [22]:
m.p1.pos

array([1, 1])

In [23]:
m.p1.vel += mol.get_force()*dt/mol.p1.m
print(m.p1.vel)

AttributeError: module 'molecule' has no attribute 'get_force'

In [3]:
p1 = par.Particle(np.asarray([0.2,0.2]),1)
p2 = par.Particle(np.asarray([0.8,0.8]),2)
m = mol.molecule(p1.pos,p2.pos,p1.m,p2.m,1,0.5)

In [5]:
waitwhere do you call get_displ

[]

In [ ]:
i thikn i should replace withh  get displ oka lets do 